### ISSUE TITLE
Sort by playlist order?

### ISSUE THREAD

**Issue by katherinehackworth** [halsafar/BeatSaberSongBrowser#101]
Not sure if this needs implementation here or in PlaylistCore, but it'd be nice to be able to sort custom playlists by playlist order, so that way they're in the order they were listed by the playlist creator.

**Comment by halsafar** [comment]
Next release of SongBrowser will support the official playlists loader via plugins like PlaylistLoaderLite.  I'll add back in the "Original" sorting method if the order is preserved by the internal loader.

**Comment by halsafar** [comment]
The "x" to cancel sorting will sort by the original order which when using playlists is the playlist order.
