### ISSUE TITLE
PlaylistCore sorting support

### ISSUE THREAD

**Issue by katherinehackworth** [halsafar/BeatSaberSongBrowser#102]
I was told that custom playlist sorting would need to be implemented on the SongBrowser side, rather than the PlaylistCore/PlaylistLoaderPlugin side. Is this still possible as with 1.5.0 given the UI changes?

**Comment by halsafar** [comment]
Definitely.  This is the next feature I plan to work on.

**Comment by katherinehackworth** [comment]
Did 1.8.0 break more stuff with regards to implementing this feature?

**Comment by halsafar** [comment]
I just got this working.  I'll give it some testings and perhaps upload a test build to the discord channel.

This supports the official Playlist loader, which by extension should be any Plugin which uses it (PlaylistLoaderLite for example).

Next release should have this.

**Comment by halsafar** [comment]
Released.  Approval on BeatMods is taking awhile so here you go.
https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/6.0.6
