### ISSUE TITLE
SongBrowser causing large lag spikes periodically

### ISSUE THREAD

**Issue by HappyCerberus** [halsafar/BeatSaberSongBrowser#106]
When I install Song Browser, the entire game will hitch every couple of seconds, both in menus and in maps.

**Comment by halsafar** [comment]
The lag spikes are likely coming from SongDataCore, a dependency.

The most recent update to both SongDataCore (1.3.0) and SongBrowser (6.0.4) should hopefully help.  Give it a spin and report in.  The new releases are on github already.

**Comment by halsafar** [comment]
Should should be definitely fixed with 1.3.1 of SongDataCore as we again cut the number of instantiated objects in half (over 1.3.0 which had done similar as well).

**Comment by HappyCerberus** [comment]
Sorry, forgot to report in :-) Yes, it's fixed now.
