### ISSUE TITLE
Filter by ranked,unranked is not working.

### ISSUE THREAD

**Issue by balu100** [halsafar/BeatSaberSongBrowser#110]
First issue:I cant filter ranked or unranked songs, i can click it but nothing happens if i click on it
Second issue i cant sort by PP,Stars,upvotes,rating,heat but i can sort by title,author,newest,yourplays

![image](https://user-images.githubusercontent.com/5224983/79642141-2bec2900-819c-11ea-8dac-767529fdb894.png)

**Comment by balu100** [comment]
Deleting C:\Users\%Username%\AppData\Local\Temp\Hyperbolic Magnetism\Beat Saber\WebCache solved it

**Comment by Sprinterr** [comment]
For me, deleting WebCache didnt solve problem. I had to delete Hyperbolic Magnetism folder
