### ISSUE TITLE
Custom SongSortMode

### ISSUE THREAD

**Issue by PulseLane** [halsafar/BeatSaberSongBrowser#111]
It'd be nice if there was a custom SongSortMode similar to the custom SongFilterMode. I had to do some pretty hacky things to get custom sorts working and it's definitely possible for any SongBrowser update to break it, so an official custom sort would be really helpful.

**Comment by halsafar** [comment]
Sure, I can do that for you.  Should be straight forward to add.

**Comment by halsafar** [comment]
I'll sneak this into the next release.  Got playlist support working so a release is due.

**Comment by halsafar** [comment]
Released.  Approval on BeatMods is taking awhile so here you go.
https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/6.0.6

**Comment by PulseLane** [comment]
Great, thank you so much!
