### ISSUE TITLE
Allow Filtering/Shuffling/Random for Custom Playlists

### ISSUE THREAD

**Issue by Xebarsis** [halsafar/BeatSaberSongBrowser#112]
I use Beatlist to create custom playlists, and the PlaylistLoaderLite mod to actually play the custom playlists. Unfortunately the BeatSaberSongBrowser is not functional in playlists; the interface for it doesn't even show up.

One of my favorite features of your mod is to be able to shuffle the list or pick a random song, but it can't be done in a playlist. I could just shuffle the customlevels playlist, but then I will have a chance of randoming songs that I know I don't want to play. For example, I have a folder that contains songs that I know are beyond my current skill level, and I have an expert+ only folder that has songs that only have the one difficulty, which my wife wouldn't want to random because that's beyond her skill level.

Could you please implement the functionality for the BeatSaberSongBrowser to work in playlists?

**Comment by halsafar** [comment]
I just got this working.  I'll give it some testings and perhaps upload a test build to the discord channel.

**Comment by halsafar** [comment]
Branch playlist-support has the work in testing.

**Comment by halsafar** [comment]
Released.  Approval on BeatMods is taking awhile so here you go.
https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/6.0.6

**Comment by Xebarsis** [comment]
Thank you!
