### ISSUE TITLE
Gets rid of the A-Z scrolling of the “All Songs” playlist

### ISSUE THREAD

**Issue by Johnny0403** [halsafar/BeatSaberSongBrowser#116]
As the title says, it removes some useful base game functionality of the "All Songs" playlist in the playlist tab. In the base game there's a scrollable A-Z bar on the side but with songbrowser installed that bar disappears and the ui is just replaced with the normal songbrowser UI.

**Comment by halsafar** [comment]
Confirmed, see if I can figure this out for the next release.

**Comment by redegg89** [comment]
Works in 1.21. No clue what changed, since I didn't think this worked in 1.19

**Comment by halsafar** [comment]
Been awhile but I think when I explored this I found it was an issue in internal BeatSaber code.  Maybe they fixed something.
