### ISSUE TITLE
Can't display UI

### ISSUE THREAD

**Issue by wgzeyu** [halsafar/BeatSaberSongBrowser#117]
About once or twice a month I see a user in the Chinese community asking, all their other mods work fine, only SongBrowser doesn't show the UI.
A clean install doesn't solve the problem either.
![](https://wgzeyu.gtxcn.com/img/20200821/QQ%E5%9B%BE%E7%89%8720200821083550.png)

Today I saw someone asking about it again, and here's the log he provided: 
[https://wgzeyu.gtxcn.com/img/20200821/Logs.zip](https://wgzeyu.gtxcn.com/img/20200821/Logs.zip)
Game version: 1.11.0
SongBrowser version: 6.0.7

**Comment by wvillarrealErgo** [comment]
It never worked for me, i never see the Favorite button or a way to manage playlists/favorites inside the game.

Same game version and Plugin release 18/08/2020 17:03

**Comment by halsafar** [comment]
Closing until we get more info.  This bug report is a few versions behind and a lot has changed since.
