### ISSUE TITLE
Support Latest Update v1.12.1

### ISSUE THREAD

**Issue by halsafar** [halsafar/BeatSaberSongBrowser#120]
SongBrowser is likely broken.  Finding out.

**Comment by halsafar** [comment]
Yes, it is broken.  Will need a redesign.

**Comment by techy2493** [comment]
Is there anything that we can do to help with this?

**Comment by halsafar** [comment]
Almost have some of the UI modifications done so we can start playing around with the core functionality.  Once I commit this we can start chipping off pieces.  Happy to discuss in Discord if you want to coordinate.

The important conversation is around what the plans for SongBrowser is.  Currently I'm just bringing the SongBrowser UI back but now on the bottom of the level selection view rather than the top.  Aiming to bring back all the functionality as is (adding stats to the song stats, etc).  There is going to be some overlap with Beat Sabers in-game filtering.  We also might be able to do away the filters sub menu and augment the in-game one.

**Comment by halsafar** [comment]
Branch is v1.12.1-support if you want to take a look.

Things are coming together.  The UI is working-ish.  For some reason the cloned Buttons are not clickable.

If you hack around not being able to click the buttons then the next issue is acquiring the current post-filtered songs and then sorting/filtering them again.

**Comment by halsafar** [comment]
Nothing is clickable because they are being drawn outside the view controller that is their parent.

**Comment by halsafar** [comment]
Most features are working again.  Some polish required still.

**Comment by halsafar** [comment]
Everything is functional again except the delete button.  There is a few small issues that need sorting out.

**Comment by halsafar** [comment]
Published the release here:
https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/6.1.1

Lets file any new issues as new tickets.
