### ISSUE TITLE
Breaks the mainmenu: solo

### ISSUE THREAD

**Issue by d4kir92** [halsafar/BeatSaberSongBrowser#122]
after removing this plugin everything works

problem:
after entering solo and playing a song
i cant press Solo again
nothing is happening
without this plugin its working right

**Comment by halsafar** [comment]
Should be fixed in 6.1.2 release.  I'll notify here when it releases.

**Comment by d4kir92** [comment]
very nice, thank you 👍

**Comment by halsafar** [comment]
Sorry for the delay on this release.  I just released 6.1.2 which should address this: https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/6.1.2

**Comment by d4kir92** [comment]
still with 6.1.2

**Comment by d4kir92** [comment]
hope you can fix it :D

**Comment by d4kir92** [comment]
actually its fixed after reinstalling ALL mods/plugins (clean install)

the problem was not be able to press on start the map (play button)

**Comment by halsafar** [comment]
Reported as fixed.  Closing.  Thanks!
