### ISSUE TITLE
Multiplayer UI issue

### ISSUE THREAD

**Issue by swift-kim** [halsafar/BeatSaberSongBrowser#124]
![image](https://user-images.githubusercontent.com/40190588/99903574-95bb4b00-2d08-11eb-9c65-8a080abd4d86.png)

Currently the view controller canvas has a fixed radius of 125, but I think it should be a variable. In the multiplayer song selection UI the value should be 154.

**Comment by halsafar** [comment]
Fix will be in the next release.  It is now grabbing the curved radius from the appropriate spot.  154 for Multiplayer still, looks like it is 130 for Solo today.
