### ISSUE TITLE
[Request] A button to delete songs

### ISSUE THREAD

**Issue by GordonFeetman** [halsafar/BeatSaberSongBrowser#125]
This was a great feature in previous versions, I'm sad to see it go :(

**Comment by troskgol** [comment]
I also miss this neat little feature. Now I never remember to clean out the trash in my ever growing list of songs.

**Comment by troskgol** [comment]
Now I noticed it is in the latest release! Will have to throw some coffee your way halsafar!

**Comment by GordonFeetman** [comment]
I somehow missed the new version, great to see it back!

**Comment by halsafar** [comment]
Thanks everyone!
