### ISSUE TITLE
Short freeze / game lock after song ends

### ISSUE THREAD

**Issue by TheTou** [halsafar/BeatSaberSongBrowser#13]
In the new 2.3.0-RC1 release I noticed the issue that the game freezes for a short period after a song ends. I assume this is caused by the plugin fetching the song PP and stars again (at least this message is displayed at the bottom of the screen). I don't think this is necessary to run after every song. Or maybe make it asynchronous so it doesn't lock up the game.

**Comment by halsafar** [comment]
Confirmed.  

Will be fixed next release.

**Comment by halsafar** [comment]
This release should fix it:
https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/2.3.0-rc2

Give it a try and let me know.

**Comment by TheTou** [comment]
Thanks, doesn't freeze any more with 2.3.0-RC2. Seems to be fixed :) 👍

**Comment by halsafar** [comment]
Excellent!  Thanks for the report!
