### ISSUE TITLE
Delete Button present but not working

### ISSUE THREAD

**Issue by olidadda** [halsafar/BeatSaberSongBrowser#131]
Using Valve Index on SteamVR.
The delete button is present on all custom songs, it returns the menu "Delete or Cancel", but then clicking delete does nothing, other than moving you back to the main menu.

**Comment by dethkube** [comment]
If this helps, here is an example of the error when trying and failing to delete a song:
```
[ERROR @ 13:24:46 | Song Browser] Unable to delete song! Exception: System.Exception: Could not find level path. Is the selected collection a playlist?
[ERROR @ 13:24:46 | Song Browser]   at SongBrowser.UI.SongBrowserUI.<HandleDeleteSelectedLevel>b__59_0 (System.Int32 selectedButton) [0x0019c] in <1c9b633cc8484f9f8e1c8444f106313a>:0
```

**Comment by dethkube** [comment]
Seem to have narrowed it down to deleting songs through the "All Songs" tab that fails. For people currently running into this issue, you should be able to delete songs if you switch to using the "Custom Levels" tab instead.

**Comment by crimzind** [comment]
I'm having an issue with the button as well.

@dethkube I'll see if changing tabs helps.

**Comment by Stevoisiak** [comment]
Can confirm switching tabs worked for me as well.
May be worth renaming issue to "Delete button doesn't work in All Songs tab".

**Comment by halsafar** [comment]
Thanks for reporting this.  This has been fixed in master.  Will be part of the next release.
