### ISSUE TITLE
Update the mod to support the BeatSaber v1.13.2 on PC please

### ISSUE THREAD

**Issue by pea3nut** [halsafar/BeatSaberSongBrowser#132]
This is a good mod but not work on the BeatSaber v1.13.2. Can you update please? I want to delete songs in the game.

**Comment by halsafar** [comment]
Update is incoming.

**Comment by halsafar** [comment]
Update is released on GitHub.  
https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/6.1.3

Should be on BeatMods soon.
