### ISSUE TITLE
SongBrowser not working

### ISSUE THREAD

**Issue by Fatalution** [halsafar/BeatSaberSongBrowser#134]
Installed the latest version (6.1.3) - dragged DLL to the Plugins folder
No result and no change. Filters are non-existent, basically, the plugin doesn't work.
All other installed plugins successfully function.

Game version - 1.13.2

**Comment by spommerening** [comment]
Same here. Should it show up in mod assistant after installation? Seems to be simply ignored. 

Double check the version. Latest release for 1.13.2. (6.1.3)

**Comment by halsafar** [comment]
Try updating SongDataCore as well: https://github.com/halsafar/BeatSaberSongDataCore/releases/tag/1.3.6

If that doesn't work, post any logs you can.

**Comment by Fatalution** [comment]
SongDataCore DLL was simply missing. It's not on the ModAssistant yet as well. That was the issue, thanks for the heads up!

**Comment by spommerening** [comment]
Same here. SongDataCore was missing and after having activated it, SongBrowser showed up. (Version 6.1.4 now) 

Thanks a lot!!!
