### ISSUE TITLE
Unresolved references when compiling in Visual Studio 2019

### ISSUE THREAD

**Issue by Stevoisiak** [halsafar/BeatSaberSongBrowser#136]
### Issue
When I try to compile BeatSaberSongBrowser in Visual Studio 2019, I get hundreds of unresolved dependency errors for SongCore, HMUI, UnityEngine, and several other packages.

![Unresolved dependency errors](https://user-images.githubusercontent.com/1330770/107086372-e8fd4f80-67c7-11eb-8e08-438f0d787b1f.png)

### Steps to reproduce
1. Locally clone BeatSaberSongDownloader.
2. Open SongBrowser.sln in Visual Studio Community 2019.
3. Click Build > Build Solution.

### Additional Info
I see many of these packages listed as dependencies in the Solution Explorer. Presumably I need to manually acquire these dependencies myself, (ie: [SongCore](https://github.com/Kylemc1413/SongCore)), but I don't know how to add the files to the project to fix the dependencies.

**Comment by halsafar** [comment]
You need to create a file to specify your Beat Saber installation folder:

/SongBrowserPlugin/SongBrowser.csproj.user
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <ProjectView>ProjectFiles</ProjectView>
    <BeatSaberDir>D:\Games\Steam\SteamApps\common\Beat Saber</BeatSaberDir>
  </PropertyGroup>
</Project>
```
