### ISSUE TITLE
Newer Ranked Songs

### ISSUE THREAD

**Issue by truality-dev** [halsafar/BeatSaberSongBrowser#138]
For some reason the newer ranked songs, won't show a star or anything rank related, it just says NA, I just tried to reninstall, didn't work, also tried redownloading the map, idk if its my game or a bug.

**Comment by halsafar** [comment]
Discussed this on Discord with some folks.  This should be fixed.  Care to confirm?

**Comment by HappyCerberus** [comment]
I have the same problem with the current version.

**Comment by HappyCerberus** [comment]
@halsafar And just to clarify, this is unrelated to the previously fixed API change issue. This is something new.

**Comment by truality-dev** [comment]
Seems to be fixed now!
