### ISSUE TITLE
MultiPlayer UI filtering\sorting issue

### ISSUE THREAD

**Issue by gonaik** [halsafar/BeatSaberSongBrowser#139]
If you start an online game right after starting the game then you won't have the sort\filter by UI loaded.
![image](https://user-images.githubusercontent.com/58854564/107864135-49dcf580-6e62-11eb-8992-d817a01c2810.png)

Good news is that there is a workaround, just need to go into solo first then you will get the Sort\Filter by UI in online game.
![image](https://user-images.githubusercontent.com/58854564/107864080-c28f8200-6e61-11eb-97f7-1532ddaa932b.png)

**Comment by halsafar** [comment]
I've fixed this in master.  Next release will include the fix.
