### ISSUE TITLE
[Feature request] Add BPS as a filter

### ISSUE THREAD

**Issue by MattDarkPro** [halsafar/BeatSaberSongBrowser#140]
I'd like to ask if you could maybe check out if it's possible to have a new sort button by BPS? It'd make finding harder / easier songs in my songs

**Comment by halsafar** [comment]
Yup that data is readily available on each song.  Easy to add a sort by BPS.  I'll see about adding this in the next version.

**Comment by Xandaros** [comment]
NJS would be really nice, too

**Comment by halsafar** [comment]
Released in 6.1.6.  Not NJS.
