### ISSUE TITLE
[Request] Filter for requirements

### ISSUE THREAD

**Issue by Xandaros** [halsafar/BeatSaberSongBrowser#147]
An option to quickly find maps that make use of Chroma/MappingExtensions/NoodeExtensions would be great.
I suspect filtering for one particular extension wouldn't make for great UI but just hiding everything that doesn't use any would be nice.

**Comment by Meivyn** [comment]
@halsafar This should probably be closed after merging #155.

**Comment by halsafar** [comment]
Yup this is working well if you have the CustomJsonData plugin installed.
