### ISSUE TITLE
clicking the heart icon to add a song to the favorites list causes the song list to jump back to the top

### ISSUE THREAD

**Issue by telos00** [halsafar/BeatSaberSongBrowser#149]
whenever I click the heart icon to add a song I just played to the favorites list, the song list jumps back to the top of the list.

this makes the list hard to use when you have a lot of custom songs (100s or 1000s), because then you lose your place and have to scroll down page by page to get back to where you were so you can keep going down the list playing songs.

it would be nice if this didn't happen.

**Comment by halsafar** [comment]
Reproduced on my side, confirmed as super frustrating.  Fix incoming.

**Comment by halsafar** [comment]
So I've confirmed it is actually not SongBrowser causing this.  Seems to be a bug in the base game.  At least I can reproduce it without any plugins installed.

With that said I have a solution in mind.

**Comment by halsafar** [comment]
I've partially fixed this.  It works as expected now for all views except if you are viewing only your favorites.  If you are viewing your favorites list and remove a favorite song the game forcefully resets everything.  It will take a bit longer to solve that.  However if you are on any other view like Custom Songs, All Songs, etc, then toggling favorites now maintains position.
