### ISSUE TITLE
List back to top when loading more songs

### ISSUE THREAD

**Issue by Eradev** [halsafar/BeatSaberSongBrowser#150]
When you load more songs at the bottom of the list, you get sent back to the top of the list and you have to scroll back down again. It didn't do this before.

**Comment by halsafar** [comment]
Are you using Downloader to download some songs?

**Comment by Eradev** [comment]
Ah yeah sorry. It's the wrong plugin. My bad!

**Comment by halsafar** [comment]
Yes this is likely a downloader issue but could also be a bug in Beat Saber itself.  Check this SongBrowser issue (https://github.com/halsafar/BeatSaberSongBrowser/issues/149).  ReloadTable() in BeatSaber itself resets the position to the top and fails to Reselect the appropriate row.  

I'm looking into adding a harmony patch to fix this for the above favorites issue.
