### ISSUE TITLE
[Feature Request] Key search for downloaded songs

### ISSUE THREAD

**Issue by Solaris9** [halsafar/BeatSaberSongBrowser#151]
It would be nice to use a songs key to search for it as it's a few characters and unique to that song instead of searching for a specific keyword and manually sifting through your songs and figuring out one of the ten songs the result shows is the one you want.

It could have the same `Key` button as BeatSaverDownloader to search for songs with that key, I'm not sure how the game handles those as the keys are for beatsaver and I believe the game uses a hash of the song info.

**Comment by halsafar** [comment]
Done.  Seems to work well without slowing down the search feature at all.  Should be available in the next release. I'll leave this open until then.
