### ISSUE TITLE
Deleting songs resets the position to the top of the list

### ISSUE THREAD

**Issue by sluncer** [halsafar/BeatSaberSongBrowser#158]
When deleting a song the position gets reset to the top of the list. This current behavior is similar to what adding a song to the favorites used to be before it was fixed. 

**Expected Behavior**: Deleting a song should maintain the current position in the song-list and move on to the song next to the deleted one.  
**Current Behavior**: Deleting a song resets the current position to the beginning of the current song list. 
**How to Reproduce**:  Selecting a song in a list and deleting the delete button.

**Comment by BlazingTwist** [comment]
Sorry for the spam, for some reason my local branch was targeting the master branch of my remote.
