### ISSUE TITLE
Sort/Filter by genre

### ISSUE THREAD

**Issue by Razzeee** [halsafar/BeatSaberSongBrowser#16]
If we're lucky beatsaver will soon carry genres. So it would be very nice, to be able to filter by genre.

https://github.com/Byorun/beatsaver-laravel/pull/35

**Comment by halsafar** [comment]
Agreed.  I'm working on this and a few other sort and filters.  This might not make it into the next release but should follow soon after.

**Comment by halsafar** [comment]
Leaving this up to EnhancedFilters.  There is just way to many genres to have a reasonable UI over it.  Genre's are also being self-supplied by song makers so it is somewhat a mess.
