### ISSUE TITLE
Sort by Mapper

### ISSUE THREAD

**Issue by symphonic643** [halsafar/BeatSaberSongBrowser#161]
I'm honestly surprised that this hasn't been integrated yet since it seems like such a core piece of information. It would be great to be able to sort/filter by mapper when trying to find maps done by the same person.

**Comment by halsafar** [comment]
Agreed.  This should be easy to add.  I'll get this done soon and post an update here.

**Comment by symphonic643** [comment]
Thank you so much! Looking forward to it. I find I really enjoy a lot of certain mappers, so this is a great way to sort when I've got a jumbled bunch of songs and playlists and am looking for more of a certain mapper that I may already have downloaded, but not realize.
