### ISSUE TITLE
Song list shows for 1 frame

### ISSUE THREAD

**Issue by Khosumi** [halsafar/BeatSaberSongBrowser#165]
Default song browser works fine, modded breaks as the video shows.
Restarting the game doesn't fix it, reinstalling the mod doesn't either. 

https://www.youtube.com/watch?v=AB67fvJohJo

**Comment by SmokyJoe88** [comment]
same issue here.

**Comment by halsafar** [comment]
This is a duplicate of #166, closing in favor of the discussion there.  Thanks for the report.
