### ISSUE TITLE
Filtering by Ranked no longer works

### ISSUE THREAD

**Issue by RogueMissile** [halsafar/BeatSaberSongBrowser#166]
I believe the BeatSaver API change may have broken the Ranked filtering setting? Unless it is an issue on my end but while I can still see the star rating on ranked maps and their details on the leader board, the filter button appears blank but filtering by unranked shows everything. 

Also, the Ranked PP % icon on the map info is always 0%.

**Comment by tipouik** [comment]
i got exactly same issue, i was wondering ifit's only on my side or not, seems not :)
i can see star rating, but can't sort by ranked maps

**Comment by halsafar** [comment]
Unfortunately this is correct.  The scraper is unable to fetch PP for a song currently. It is working on being resolved.

This also reveals a bug in SongBrowser were you can get stuck with an empty set of songs if you try to filter by ranked.  Cancel the filter, go back to main menu and enter solo mode again should fix it.

I'll keep this open to update on the PP fix.

**Comment by RogueMissile** [comment]
Thanks for replying and your work.
I tried your suggestion about the ranked filtering but unfortunately it remains blank every time. Including restarting the game. I tested it multiple times over.

**Comment by halsafar** [comment]
I'll publish an update today that should tackle this properly for everyone.  Also the PP rating should be fixed I've been told which will also fix this issue.

**Comment by halsafar** [comment]
Alright, with the BeatStar scrape producing valid PP data again it looks like Filter By Ranked is also working again.

I'll leave this open for a awhile for someone to confirm.
