### ISSUE TITLE
cannot play songs

### ISSUE THREAD

**Issue by ClearestCrayon** [halsafar/BeatSaberSongBrowser#168]
when ever i tried to load up a song it does not give me the option to play them it justs me the jpg of the song but no way to play them. this is for all the songs even the ost songs that come with the game

**Comment by halsafar** [comment]
Can you provide the latest.log file a run where this happens?

The game updated today so that might also be the cause.

**Comment by halsafar** [comment]
Not enough info to investigate further. Feel free to add some more info if this happens again and we can open this issue back up.
