### ISSUE TITLE
Random button gives blackscreen

### ISSUE THREAD

**Issue by nabel0** [halsafar/BeatSaberSongBrowser#171]
The button for random maps does not work and gives a black screen. 
If the filter is random and you click on it, the game also gives a black screen.

**Comment by halsafar** [comment]
Confirmed, and the fix is in.  Will do a release shortly.

**Comment by halsafar** [comment]
Give this release a try:
https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/6.3.1

**Comment by megamaz** [comment]
[_latest.log](https://github.com/halsafar/BeatSaberSongBrowser/files/7117548/_latest.log)
Error still occurs with 6.3.1 installed, here's the log file. (NullReference errors happen a lot. If it's trying to force-launch a map I suggest you add a setting to enable/disable that)

**Comment by halsafar** [comment]
The log shows you have version 6.3.0 still installed.  Make sure the game is fully closed and then copy the dll into the plugins folder.

**Comment by nabel0** [comment]
I can confirm it's fixed...Working fine now...

**Comment by halsafar** [comment]
Thanks for confirming @nabel0 .

@megamaz There is a setting for the Random - Instant Queue feature but it was accidentally enabled by default in the 6.3.0 release, it is also broken in 6.3.0.  In 6.3.1 it is no longer enabled by default, you can enable it in the in game Song Browser settings if you want it back.
