### ISSUE TITLE
Game fades to black when randomly sorting songs in 1.17.1

### ISSUE THREAD

**Issue by BrandonDusseau** [halsafar/BeatSaberSongBrowser#173]
This affects SongBrowser 6.3.0 in Beat Saber 1.17.1. When I select the "random" die or choose to sort ascending/descending while the song list is active, the game screen fades to black and remains that way until the game is restarted. This seems to only impact the ascending/descending button when set to sort random.

Logs and a video demonstrating the issue are attached.

https://user-images.githubusercontent.com/3901864/132883349-a27d74b5-7b1a-4813-98cc-b045f7de9365.mp4

[Player.log](https://github.com/halsafar/BeatSaberSongBrowser/files/7145035/Player.log)
[output_log.txt](https://github.com/halsafar/BeatSaberSongBrowser/files/7145043/output_log.txt)

**Comment by halsafar** [comment]
Fixed in https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/6.3.1

6.3.1 is not yet approved on beatmods so you need to manually download it.

Enjoy!
