### ISSUE TITLE
Beat Saber 1.20.0 Support

### ISSUE THREAD

**Issue by halsafar** [halsafar/BeatSaberSongBrowser#185]
Place holder for discussion

**Comment by DieSteinhose** [comment]
The plugin will not load in 1.20.0, I tried 6.3.4. I put the dll in the plugin folder, located in the root directory of the installation. After that I executed IPA. However, the plugin is not loaded, am I doing something wrong?

**Comment by IlinAleksey** [comment]
@DieSteinhose Also had the same problem, installing SongDataCore plugin helped: https://github.com/halsafar/BeatSaberSongDataCore

**Comment by wlsnbilyb** [comment]
> @DieSteinhose Also had the same problem, installing SongDataCore plugin helped: https://github.com/halsafar/BeatSaberSongDataCore

Can confirm, had the same problem and this fixed it!
