### ISSUE TITLE
Beat saber crashed by SongBrowserSongMetadata.json

### ISSUE THREAD

**Issue by Mofuka** [halsafar/BeatSaberSongBrowser#192]
(I can not speak English very well, So i used a translator)

BeatSaber crashed when using this plugin on 1.20.0 and 1.21.0 versions

So i tried delete **"SongBrowserSongMetadata.json"** file 

then BeatSaber was not crashed

But, that file will be regenerated

must delete the file before running BeatSaber each time

So is there a way to prevent that file being created?

**Comment by Mofuka** [comment]
I found a solution

goto BeatSaber -> UserData

and click file Properties for SongBrowserSongMetadata.json

and click the Security tab and deny all permissions.

Then will be no crash

**Comment by halsafar** [comment]
I'm wondering if this feature using the SongMetaData file needs to be made optional and off by default.

**Comment by alargepileofash** [comment]
> goto BeatSaber -> UserData
> 
> and click file Properties for SongBrowserSongMetadata.json
> 
> and click the Security tab and deny all permissions.
> 
> Then will be no crash, no regenerated

how did you do this?

**Comment by IlinAleksey** [comment]
Also noticed SongBrowserSongMetadata.json is getting regenerated each time the game is launched. I am pretty sure it's caused by this arcane bug in BSIPA: https://github.com/nike4613/BeatSaber-IPA-Reloaded/issues/82
Fixed this issue locally by changing type of `AddedAt` field to `string`

**Comment by halsafar** [comment]
Next release fixes this and offers an option to disable it if it causes issues in the future.
