### ISSUE TITLE
Is there a way to restore the most played after a move of the folders

### ISSUE THREAD

**Issue by dwaynelarose** [halsafar/BeatSaberSongBrowser#193]
I had to restore some data for the BSLegacy folder and it appears that my most played data is gone.
What do I need to backup in future to keep that data?

**Comment by halsafar** [comment]
The per song play count is not stored by SongBrowser.  It is stored in Beat Saber's AppData folder here: `%USERPROFILE%/AppData\LocalLow\Hyperbolic Magnetism\Beat Saber`.

You will also want to backup the `UserData` folder located in your Beat Saber install directory.  That folder contains the settings for all of your mods, including SongBrowser.

SongBrowser does store when a song was first seen (first added), this files is located in `BeatSaberInstall/UserData/SongBrowserSongMetadata.json`.
