### ISSUE TITLE
random functionality ?

### ISSUE THREAD

**Issue by 1immortal** [halsafar/BeatSaberSongBrowser#195]
Hi guys,

I know that there's an option of shuffling the playlist, is there any possible way of shuffling and playing the selected ones ?
I want to be able to set the difficulty and just press "Hit me" with same level songs.

Thanks for your all hard work!

**Comment by 1immortal** [comment]
exactly, or from all available songs, not from a specific playlist.
I'm using 1.2.1 BS with the supported BMBF, have some 700 songs in it, not divided into playlists.
If its possible to set to **hard** and just get random songs from all available, that would really be awesome :)

**Comment by halsafar** [comment]
I think you might be able to do this in the next release already, I'll play around.  The next release has "filter by difficulty" so you can say filter out all songs without "Hard".  The random button shuffles whatever song list you have up (go to All Songs for everything).  The difficulty should remain on whatever you had selected before clicking the Random button. If you enable the "Random Instant Queue" setting you could just spam the random button for endless hard songs.  I'll double check this all works.

**Comment by 1immortal** [comment]
that would be awesome!
Thanks again!

**Comment by halsafar** [comment]
Yah I can confirm this works in the upcoming release:
- Enable Filter for the difficulty you want
- Select that difficulty on whatever song is currently highlighted
- Click random button, selected difficulty is preserved (since the filter guarantees it exists)

**Comment by 1immortal** [comment]
Tanks!!!!!

**Comment by 1immortal** [comment]
sorry for asking, but do you have any rough estimation of the next release?

**Comment by halsafar** [comment]
Not sure if this is still relevant to you, sorry it took so long (life has been busy): https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/6.4.0
