### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by xJon** [halsafar/BeatSaberSongBrowser#197]
Not sure if I'm missing any dependencies? Using `1.25.1` on Steam.

**Comment by rctts** [comment]
youre probably missing dependencies, mine seems to work fine so i assume itd be dependencies :p

**Comment by xJon** [comment]
@rctts I can't find a list of required dependencies anywhere.

**Comment by rctts** [comment]
itd probably be the basic dependencies most mods use, just install most of the libraries you see in the libraries tab on modassistant (idk what libs it depends on exactly so my apologies if this really didnt help lol)

**Comment by xJon** [comment]
@rctts I have those installed:
![image](https://user-images.githubusercontent.com/8945347/196791909-bf7089a4-607c-4a6f-a9bc-bd236fa02fc5.png)
![image](https://user-images.githubusercontent.com/8945347/196791948-477ac8d7-9e68-487d-9e07-be832986c448.png)

**Comment by demck85** [comment]
yeah, not working for me either. it was at one point, but it was off screen and could only see that top of the icons and such

**Comment by demck85** [comment]
> yeah, not working for me either. it was at one point, but it was off screen and could only see that top of the icons and such

i found it sort of works in the custom level song listing in party mode, but the button are off screen still. In all song listing, it still didn't show up

**Comment by xJon** [comment]
I ended up using https://github.com/kinsi55/BeatSaber_BetterSongList instead.

**Comment by halsafar** [comment]
Dependencies are listed in this manifest.json file: https://github.com/halsafar/BeatSaberSongBrowser/blob/master/SongBrowserPlugin/manifest.json

**Comment by demck85** [comment]
turned out to be a setting in the custom avatars that raised the floor to high and was cutting things off
