### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by NathanSweet** [halsafar/BeatSaberSongBrowser#20]
I have played 150+ songs and marked the best as favorites. I would like to share this with other users. An easy way to do that would be to use a playlist. BeatDrop can create playlists, but BeatDrop doesn't see the song browser favorites, making it tedious to recreate the playlist. Maybe the song browser could store favorites in a playlist instead of `song_browser_settings.xml`? It could just overwrite a playlist file when favorites are saved. I wouldn't mind if it saved them in both places.

The above would be sufficient for my needs, but it would also be super cool to be able to browse, create, and edit playlists in the song browser!

**Comment by halsafar** [comment]
Absolutely.  I'll get this done for next release.  I also find myself needing to share my favorites and having no nice except to override / manually merge song_browser_settings.  

I'll upgrade existing favorites into a playlist and remove them upon success.

**Comment by halsafar** [comment]
So I've gone and addressed the easiest part of this request.  Favorites convert to a playlist, otherwise everything is the same.  

The only issue left is which folder to store the Playlist in.

I cannot assume a user is using Beat Drop.

Playlists can go in Beat Drop's Playlist folder OR Beat_Saber_Install/Playlists/.

Currently BeatDrop only reads from its location.

**Comment by NathanSweet** [comment]
Super awesome! Thanks for your work!

FWIW, I would say `Beat_Saber_Install/Playlists/` makes sense. If users want to see playlists in-game, that is where they have to put them anyway. BeatDrop should really use that folder, not in its installation.

**Comment by halsafar** [comment]
I chatted with a Beat Drop dev and they confirmed next version will read from Beat Saber's install folder.

**Comment by halsafar** [comment]
Release is out, give it a try and let me know: 
https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/2.3.4

Typically when you open the flood gates on something like custom songs you will get a uniform distribution of amazing to poor in terms of quality.  It is the nature of things.  

We can however address this issue with some UI tweaks.  Community voting is already happening on BeatSaver.  I'll be hopefully improving this with each new release.  Things such as the rating on BeatSaver would be useful to see.

**Comment by NathanSweet** [comment]
I've been using it and it works great! Thank you!

I don't think the distribution is uniform at all, it's maybe 5-10% good songs and the rest range from bad to terrible. Sometimes I can spend a whole 2 hour session trying new songs and find only 1 or 2 good ones. Showing votes would be great and I'm all for having as many tools that help, but like I was saying above, voting has it's own problems: older songs will have more votes, new songs might be great but have few votes, and to be honest the chance that most of the people voting are idiots is very high. 😆

My stupidity rating idea would basically flag songs as being unfun, as much as can be determined analytically without false positives. Minor infractions would affect the score a little, excessive stupidity detections would affect it more. If it provided insight into which detections were found, it could even be useful for mappers to improve their maps before publishing them (especially important since authors don't have a way to update/revise maps!).

Detections are subjective of course, eg I dislike songs that repeat the exact same sequence more than 3-4 times, or that have many subsequent notes all the same direction (my poor wrists!), or throw the notes at your eyes too much, etc. Maybe each type of detection could be disabled or weighted by the user, but even if not configurable, the stupidity score would be a great data point that users could consider, if they choose. If it were configurable and built into a song browser / downloader / search, it could be used as search criteria to find songs more likely to be enjoyable for a particular user. That is super powerful and could have a big, positive impact.

I think it's crucial for Beat Saber to have good tools to sort the large amount of content people are creating.
