### ISSUE TITLE
Random sort refreshes too often

### ISSUE THREAD

**Issue by xhuytox** [halsafar/BeatSaberSongBrowser#22]
After initially selecting random sort, the random list is generated. However, this list gets randomized automatically after a song is completed. The expectation would be the random list would the same until random is pressed again.

**Comment by halsafar** [comment]
Agreed.  I'll make this change next release.  Thanks for the report.

**Comment by halsafar** [comment]
Fixed in: https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/2.3.4

Give it a try and let me know.

**Comment by xhuytox** [comment]
LGTM. Closing issue.
