### ISSUE TITLE
Sort inversion not preserved

### ISSUE THREAD

**Issue by xhuytox** [halsafar/BeatSaberSongBrowser#23]
When coming back to the browser from the main menu or after completing a song, the song sort mode is correct, but the inversion is not preserved. For example, a player selects to sort by song names in descending order (Z to A). After a song is completed, the sort goes back to ascending order. My guess is the settings needs to save the last the InvertingResults flag as well as sort mode.

**Comment by halsafar** [comment]
Confirmed.

Fixed it in devel branch already.  Will be out in next release.  I'll post here for confirmation.

**Comment by halsafar** [comment]
Fixed in: https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/2.3.4

Give it a try and let me know.

**Comment by xhuytox** [comment]
LGTM. Closing issue.
