### ISSUE TITLE
Party Mode UI Bug

### ISSUE THREAD

**Issue by xhuytox** [halsafar/BeatSaberSongBrowser#24]
See below. It looks like it only affects Party Mode.

![20181108204739_1](https://user-images.githubusercontent.com/20061642/48244125-d69dcc80-e398-11e8-9351-b994b8d8baeb.jpg)

**Comment by halsafar** [comment]
Confirmed.  This will be fixed in the next release.  

Sorry for the delay on responding to this.

**Comment by halsafar** [comment]
This is resolved in 2.4.1.  Let me know if you still have an issue.
