### ISSUE TITLE
Performance Points not showing up

### ISSUE THREAD

**Issue by tu0mas** [halsafar/BeatSaberSongBrowser#25]
Having this issue since last week. PP aren't displayed like usual (for all the songs).

![48305839-4abfa800-e532-11e8-8eef-f7fe89858a3d](https://user-images.githubusercontent.com/26165838/48647031-ffead800-e9ea-11e8-958b-eb18fef5acc2.png)

I tried to reinstall Score Saber, SongBrowser/Loader as well. Also reinstalling Windows. It has no effect. Any ideas why?

**Comment by halsafar** [comment]
Very strange.  It is still working for me.  I even tested that particular song.  

Can you enable the console log when starting Beat Saber?  Add `--verbose` as a command line argument.

There might be some exceptions or errors in the log that would point to what is going on.  If you can get me that log I can likely fix it.

**Comment by tu0mas** [comment]
Sure. Here's the result:

`Beat Saber
[ERROR] Could not load BeatSaberHTTPStatus.dll! System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <e1a80661d61443feb3dbdaac88eeb776>:0
  at IllusionInjector.PluginManager.LoadPluginsFromFile (System.String file, System.String exeName) [0x00026] in <be160f5ca99440c98e1b1995202ab6fe>:0
Running on Unity 2018.1.6f1
-----------------------------
Loading plugins from F:\SteamLibrary\steamapps\common\Beat Saber\Plugins and found 22
-----------------------------
 Discord Presence: v2.0.2
 Beat Saber Tweaks: 3.3.2
 BeatSaver Downloader: 2.6.3
 CameraPlus: v2.0.1
 CustomColorsEdit: 1.3.0
 CustomFailText: 1.0.0
 Custom Platforms: 2.3.0
 CustomMenuMusic: 0.1.0
 Custom Menu Text: 2.1.0
 Saber Mod: 2.5
 DebrisRemover: 1.0.1
 EnhancedTwitchChat: 0.3.3
 Full Combo Display: 1.1.1
 Immersive Mode: 1.0.1
 Perfection Display: 1.3.2
 Practice Plugin: v3.0.2
 ProgressCounter: 4.0
 ShitMapDetector: 0.1.1
 Song Browser: v2.3.4
 Song Loader Plugin: v4.3.2
 Beat Saber Twitch Integration: 2.0.2_bs-0.11.2
 Unofficial Leaderboard by Umbranox: 1.7.2
-----------------------------
Tweak Manager started.
[BeatSaverDownloader @ 12:37] Loaded config
[BeatSaverDownloader @ 12:37] Song Browser installed, disabling Song List Tweaks
Found 12 sabers
Immersive Mode: System.IO.FileNotFoundException: Could not load file or assembly '0Harmony, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: '0Harmony, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'
  at IllusionInjector.CompositePlugin+<>c.<OnApplicationStart>b__3_0 (IllusionPlugin.IPlugin plugin) [0x00000] in <be160f5ca99440c98e1b1995202ab6fe>:0
  at IllusionInjector.CompositePlugin.Invoke (IllusionInjector.CompositePlugin+CompositeCall callback) [0x00015] in <be160f5ca99440c98e1b1995202ab6fe>:0
Setting breakpad minidump AppID = 620980
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198040296837 [API loaded no]
2018-11-18 12:37:10.0782|DEBUG|TwitchIntegrationPlugin.BeatBot|Connection to twitch server established. Beginning Login.
2018-11-18 12:37:10.0971|DEBUG|TwitchIntegrationPlugin.BeatBot|Login complete Beat bot online.
2018-11-18 12:37:10.0971|DEBUG|TwitchIntegrationPlugin.BeatBot|soliela
[CustomMenuMusic] CustomMenuSongs files found 5
[CustomMenuMusic] Found 5 custom menu songs
[CustomColorsEdit] ColorManager colors set!
[CustomColorsEdit] ScriptableColors modified!
[CustomColorsEdit] PrePassLight colors set!
[CustomColorsEdit] Environment light colors set!
[CustomColorsEdit] ColorManager colors set!
[CustomColorsEdit] ScriptableColors modified!
[CustomColorsEdit] PrePassLight colors set!
[CustomColorsEdit] Environment light colors set!
[EnhancedTwitchChat] EnhancedTwitchChat initialized
[EnhancedTwitchChat] Using username justinfan1869984431
[SongBrowserModel @ 12:37 - Info] Settings loaded, sorting mode is: PP
Reading config!
Parsing pattern line "(nx)"
Added flag n successfully (currentNodeFlags: 800)!
Added flag x successfully (currentNodeFlags: 802)!
Added pattern "Bomb Inside Note"!
Parsing pattern line "(w)-(w)-(w)"
Added flag w successfully (currentNodeFlags: 10)!
Added flag w successfully (currentNodeFlags: 10)!
Added flag w successfully (currentNodeFlags: 10)!
Parsing pattern line "(w)-(w)-(w)"
Added flag w successfully (currentNodeFlags: 10)!
Added flag w successfully (currentNodeFlags: 10)!
Added flag w successfully (currentNodeFlags: 10)!
Parsing pattern line "(w)-(w)-(w)"
Added flag w successfully (currentNodeFlags: 10)!
Added flag w successfully (currentNodeFlags: 10)!
Added flag w successfully (currentNodeFlags: 10)!
Added pattern "3+ Wide Wall"!
Parsing pattern line "(*)-(*)-(x)-(a)"
Added flag * successfully (currentNodeFlags: 20)!
Added flag * successfully (currentNodeFlags: 20)!
Added flag x successfully (currentNodeFlags: 02)!
Added flag a successfully (currentNodeFlags: 04)!
Added pattern "NoteA Far Crossover w/ Bomb"!
Parsing pattern line "(b)-(x)-(*)-(*)"
Added flag b successfully (currentNodeFlags: 08)!
Added flag x successfully (currentNodeFlags: 02)!
Added flag * successfully (currentNodeFlags: 20)!
Added flag * successfully (currentNodeFlags: 20)!
Added pattern "NoteB Far Crossover w/ Bomb"!
Song Loader [INFO]: Starting full song refresh
[CustomMenuMusic] Loading file @ CustomMenuSongs\MenuMusic - Tomfoolery.ogg
[ScoreSaberDatabaseDownloader @ 12:37 - Info] Attempting to download: https://raw.githubusercontent.com/halsafar/beat-saber-scraped-data/master/scoresaber/score_saber_data_v1.json
[BeatSaverDownloader @ 12:37] Waiting for results view controller
[PlatLoader] Loading: Simple_Platform_001.plat
[PlatLoader] legacy version of customPlatform detected, updating
[PlatLoader] Loaded: Simple Platform 001 by TheMightySpud
[PlatLoader] Loading: Simple_Platform_002.plat
[PlatLoader] legacy version of customPlatform detected, updating
[PlatLoader] Loaded: Simple Platform 002 by TheMightySpud
[PlatLoader] Loading: Spectrogram_Floor.plat
creating columns
[PlatLoader] Loaded: Spectrogram Floor by Rolo
Hiding env for: Default Environment
Environment hidden
[CustomColorsEdit] ColorManager colors set!
[CustomColorsEdit] ScriptableColors modified!
[CustomColorsEdit] PrePassLight colors set!
[CustomColorsEdit] Environment light colors set!
[CustomColorsEdit] Menu colors set!
Clip loaded! 3.474 seconds long!
[EnhancedTwitchChat] Connected to twitch chat successfully!
[EnhancedTwitchChat] Channel room-id: 39752744
[CustomMenuMusic] Applying custom menu music...
[SongBrowserUI @ 12:37 - Info] Refreshing the song list view.
[BeatSaverDownloader @ 12:37] Found results view controller!
[EnhancedTwitchChat] Reinitializing sprites!
[EnhancedTwitchChat] Downloading BTTV global emote listing
[EnhancedTwitchChat] Downloading BTTV emotes for channel vredesbyrd00
[EnhancedTwitchChat] Downloading FFZ global emote listing
[EnhancedTwitchChat] Downloading FFZ emotes for channel vredesbyrd00
[EnhancedTwitchChat] Downloading twitch channel badge listing
[EnhancedTwitchChat] Downloading twitch global badge listing
[ScoreSaberDatabaseDownloader @ 12:37 - Info] Success downloading ScoreSaber data!
[SongBrowserUI @ 12:37 - Info] Refreshing the song list view.
[EnhancedTwitchChat] Web request completed, BTTV global emotes now cached!
[EnhancedTwitchChat] An error occured when requesting BTTV channel emote listing, Message: "Generic/unknown HTTP error"
[EnhancedTwitchChat] An error occured when requesting FFZ channel emote listing, Message: "Generic/unknown HTTP error"
[EnhancedTwitchChat] Web request completed, FFZ global emotes now cached!
[EnhancedTwitchChat] Web request completed, twitch channel badges now cached!
[EnhancedTwitchChat] Web request completed, twitch global badges now cached!
Song Loader [WARN]: Couldn't find or parse difficulty json F:/SteamLibrary/steamapps/common/Beat Saber/CustomSongs/Overkill/Easy.json
Song Loader [INFO]: Loaded 105 new songs in 3 seconds
[BeatSaverDownloader @ 12:37] Creating default playlists...
[BeatSaverDownloader @ 12:37] Created "All songs" playlist with 121 songs!
[BeatSaverDownloader @ 12:37] Created "Your favorite songs" playlist with 0 songs!
[BeatSaverDownloader @ 12:37] Trying to set song list levels, got 116 levels
[SongBrowserModel @ 12:37 - Info] Determining song download time and determining mappings took 3ms
[SongBrowserModel @ 12:37 - Info] No song filter selected...
[SongBrowserModel @ 12:37 - Info] Filtering songs took 0ms
[SongBrowserModel @ 12:37 - Info] Sorting song list by performance points...
[SongBrowserModel @ 12:37 - Info] Sorting songs took 1ms
[SongBrowserModel @ 12:37 - Info] Updating songs infos took 21ms
[SongBrowserModel @ 12:37 - Info] Determining song download time and determining mappings took 0ms
[SongBrowserModel @ 12:37 - Info] No song filter selected...
[SongBrowserModel @ 12:37 - Info] Filtering songs took 0ms
[SongBrowserModel @ 12:37 - Info] Sorting song list by performance points...
[SongBrowserModel @ 12:37 - Info] Sorting songs took 0ms
[SongBrowserModel @ 12:37 - Info] Updating songs infos took 2ms
[SongBrowserUI @ 12:37 - Info] Refreshing the song list view.
[SongBrowserUI @ 12:37 - Info] Checking for BeatSaber Twitch Integration Plugin...
[SongBrowserUI @ 12:37 - Info] BeatSaber Twitch Integration plugin detected: False
[SongBrowserModel @ 12:37 - Info] Determining song download time and determining mappings took 0ms
[SongBrowserModel @ 12:37 - Info] No song filter selected...
[SongBrowserModel @ 12:37 - Info] Filtering songs took 0ms
[SongBrowserModel @ 12:37 - Info] Sorting song list by performance points...
[SongBrowserModel @ 12:37 - Info] Sorting songs took 0ms
[SongBrowserModel @ 12:37 - Info] Updating songs infos took 3ms
[SongBrowserUI @ 12:37 - Info] Refreshing the song list view.
[SongBrowserModel @ 12:37 - Info] Determining song download time and determining mappings took 0ms
[SongBrowserModel @ 12:37 - Info] No song filter selected...
[SongBrowserModel @ 12:37 - Info] Filtering songs took 0ms
[SongBrowserModel @ 12:37 - Info] Sorting song list by performance points...
[SongBrowserModel @ 12:37 - Info] Sorting songs took 0ms
[SongBrowserModel @ 12:37 - Info] Updating songs infos took 3ms
[SongBrowserUI @ 12:37 - Info] Refreshing the song list view.
`

**Comment by tu0mas** [comment]
Problem solved: In CustomSongs folder, all the tracks were extracted by their name (e.g. CustomSongs\Take me out\song.ogg). You can play it but PP or Difficulty aren't shown. So you must extract the tracks by their ID (e.g. CustomSongs\8112-8167\Take me out\song.ogg).
Kinda annoying, an "Artist - Track" folder is way more explicit than a "1234-5678" folder so I can keep my CustomSongs folder "clean". Thank you for your help though. 😊

**Comment by halsafar** [comment]
Sorry I took so long to respond to this.  I am glad you figured it out.    Score saber uses song key-version for matching so at the moment we are stuck with that.
