### ISSUE TITLE
Song list scroll position resetting

### ISSUE THREAD

**Issue by brandonryan** [halsafar/BeatSaberSongBrowser#26]
Every time I exit a song, it kicks me back to the song list starting at the top. I disabled this plugin and it stopped. I'm unsure if it's just thing plugin or an incompatibility with another plugin.
I'm going to update this once I narrow down where the incompatibility is.

**Comment by brandonryan** [comment]
It's the latest tagged version.
No twitch integration.

**Comment by brandonryan** [comment]
Is there a way to turn on verbose logging?

**Comment by halsafar** [comment]
I have the cycles to address this now if it is still happening for you in 2.4.2 of SongBrowserPlugin.   It does not happen for me so we'll need to work together a bit to reproduce.

If you haven't already done this: In Steam -> Library -> (Right click) Beat Saber -> Properties -> Launch Options -> Add `--verbose`.

There is no easy way to enable verbose logging at the moment in SongBrowserPlugin.  For now I'd most interested if there is any Exceptions in the log when you return from a song.

**Comment by halsafar** [comment]
Fixed in 3.0.4 release.  Confirm?

**Comment by halsafar** [comment]
This is definitely working in 3.0.6.
