### ISSUE TITLE
Update to Beat Saber 1.12

### ISSUE THREAD

**Issue by leynebe** [halsafar/BeatSaberSongBrowser#27]
1.12 is out, but the plugin is not listen in the BeatSaberModManager.

**Comment by halsafar** [comment]
Progress is being made.  I have it mostly fully functional again.  Just some UI bug to work out still.  Hopefully have a release in the next few days.  This recent Beat Saber update had lots of UI changes and being a plugin that is pretty UI heavy it has taken a bit of a refactor.

**Comment by leynebe** [comment]
Great, thanks for the hard work!

**Comment by halsafar** [comment]
Give 2.4.1 a try.  It is working well in the most recent Beat Saber.
