### ISSUE TITLE
Delete Song Issue loading songs.

### ISSUE THREAD

**Issue by MorkOrk** [halsafar/BeatSaberSongBrowser#28]
The Delete Song  Yes / No buttons did not work.   Loading songs also takes a long time to load. I have to click around the buttons for it to finally work.

Could you also add back the up / down vote of songs.

I'm using an Oculus Rift,

Thanks, and keep up the good work.

**Comment by halsafar** [comment]
Try the recent 2.4.1 release.  It should address this.

**Comment by halsafar** [comment]
I've confirmed with a few people this is fixed.
