### ISSUE TITLE
No refresh after delete

### ISSUE THREAD

**Issue by xhuytox** [halsafar/BeatSaberSongBrowser#32]
Version 2.4.4

How to reproduce:

1) Open song list
2) Delete first song (Song will still show after deletion with not audio preview and selecting it or trying to delete it results in a stuck-menu state)

Alternatively:
1) Delete a song that's not the first (song will be removed from the list)
2) Go back to the main menu
3) Navigate to song list (deleted songs still show up on the list)

**Comment by halsafar** [comment]
Fixed this in 3.0.2.  Want to confirm?

**Comment by xhuytox** [comment]
Confirmed fixed. Thanks!
