### ISSUE TITLE
Duplicate songs

### ISSUE THREAD

**Issue by xhuytox** [halsafar/BeatSaberSongBrowser#33]
Not sure if this is a bug in the browser or in the custom song plugin, but there are songs that show up as duplicates. When you try to delete one, the other one becomes inactive as well.

**Comment by halsafar** [comment]
I've noticed this as well especially with SyncSaber installed.  Whenever SyncSaber auto updates a song it gets duplicated in the song browser.

I can fix this for next release as well.

**Comment by halsafar** [comment]
This looks fixed in 3.0.2.  Want to confirm?

**Comment by xhuytox** [comment]
Yes, confirmed. This looks fixed.
