### ISSUE TITLE
Sort by latest played

### ISSUE THREAD

**Issue by matthanson12** [halsafar/BeatSaberSongBrowser#34]
My roommate was asking about a song I played last night, could you sort by most recently played?

**Comment by halsafar** [comment]
I can add this.  I've been wanting to add some more technical sorting methods.  I'll queue this up for next release.

**Comment by matthanson12** [comment]
Awesome. Do you know who to talk to about adding the date to high scores in party mode? Sometimes when a friend beats a high score of mine I don't know if it was from when I was bad or more recently when I'm less bad lol. I assume it's a different mod?

**Comment by halsafar** [comment]
An old request.  Next release will have sort by last played.

**Comment by halsafar** [comment]
This feature is now available in 6.4.0.  Enjoy.
