### ISSUE TITLE
The newest tab sorts songs incorrectly

### ISSUE THREAD

**Issue by BlueFivesTM** [halsafar/BeatSaberSongBrowser#35]
The "newest" songs you install manually are sorted by "Date Modified" instead of "Date Created".
This means that whatever song was **created** first is put to the top of the list instead of the song you most recently added.
This is slightly annoying when trying to find the song I just installed and it would be nice to get this fixed, or atleast help me if I have went wrong somewhere

**Comment by halsafar** [comment]
Confirmed.  Will fix next release.

**Comment by WesVleuten** [comment]
This will be fixed in 3.0.2, we will use the newest date from both modified and created for newest sorting.

**Comment by halsafar** [comment]
@BlueFivesTM Do you want to confirm the fix?

**Comment by BlueFivesTM** [comment]
I can confirm that this is now fixed. Sorry for the delayed reply, I appreciate you sorting out this issue. Thanks :)
