### ISSUE TITLE
PP values are not up to date.

### ISSUE THREAD

**Issue by L1Z1X** [halsafar/BeatSaberSongBrowser#36]
Noticed this after downloading the [Top 200 PP](https://bsaber.com/top200pp/) playlist in-game and sorting by PP descending.  Many songs appear as having no PP and are just shown in alphabetical order beneath the original songs (for example [Daisuki, Evolution](https://scoresaber.com/leaderboard/92172)).  I believe my `CustomsSongs` sub-directories are all versioned correctly (`BeatSaber_Install/CustomSongs/###-###/SongName`).

It looks like the [scraped ScoreSaber file](https://raw.githubusercontent.com/halsafar/beat-saber-scraped-data/master/scoresaber/score_saber_data_v1.json) might be incomplete and missing a few songs (including the song mentioned above, Daisuki Evolution).

Any chance this file is easy to update?

**Comment by WesVleuten** [comment]
Fixed in #37
