### ISSUE TITLE
Playlist selection screen arrow is blocked

### ISSUE THREAD

**Issue by xicor333** [halsafar/BeatSaberSongBrowser#39]
If you have enough playlists, the down arrow becomes covered by one of the playlists... so you cant go down the list.

**Comment by WesVleuten** [comment]
Thanks for your bug report, to fix this issue I'd like to ask you a couple questions:
1. How many playlists do you have for this to become an issue?
2. Is this always the case or does it seem to be fixed randomly?
3. Which version are you using?

**Comment by xicor333** [comment]
1. i saw it when i was at 12. i no longer see it at 10.
2.  Might be fixed randomly, i'd have to add some more playlists and see if it comes back
3. most recent from modsaber installer

**Comment by xicor333** [comment]
seems like it most often happens if you go into the mods section before going into the playlist selection. (maybe an issue with one of the other mods?)

**Comment by WesVleuten** [comment]
Interesting issue, however we wont fix this due to plans on completely reworking the playlist interface.

Thank you for your bug report
