### ISSUE TITLE
Searching seems to break custom song lists.

### ISSUE THREAD

**Issue by williums** [halsafar/BeatSaberSongBrowser#45]
A number of users have reported that searching doesn't work, and all custom songs disappear after using the search function.

**Comment by WesVleuten** [comment]
Thank you for your report. I can confirm this will be fixed in 3.0.2

**Comment by n4ru** [comment]
Using the latest update my custom songs do not show at all. Removing the plug-in brings them back. My friend does not seem to have this issue however.

**Comment by WesVleuten** [comment]
Have you updated the SongLoader to the latest version? Please go to the mod installer and select both the SongLoader and SongBrowser and press install. Make sure you're running the new modsaber installer which can be found [here](https://github.com/lolPants/modsaber-installer/releases).

Please let me know if this resolved your issue

**Comment by n4ru** [comment]
No luck. Did a completely fresh install of Beat Saber and custom songs still don't show up if I install the mod.
