### ISSUE TITLE
random song button doesn't actually select the song

### ISSUE THREAD

**Issue by brian91292** [halsafar/BeatSaberSongBrowser#48]
When selecting the random song button, the song list appears to scroll to the position of the randomly selected song; but no song is actually selected (and thus, no preview plays, and the user has know way of knowing which song was randomly selected).

Using song browser version 3.0.2.

**Comment by xhuytox** [comment]
I think this feature is working as intended. The random feature has always generated a "shuffled" list. It is not the same as the new "dice" button in the 3.0.2 update.

**Comment by brian91292** [comment]
Ah, didn't notice the dice button. If that's the case then you're right and this issue can be closed.

**Comment by xhuytox** [comment]
A quick note though. This custom browser doesn't show the new dice button. That could be a feature request.

**Comment by brian91292** [comment]
I'm pretty sure this is just a broken feature and you're talking about a feature from song downloader possibly, which disables its song list tweaks when song browser is installed.

**Comment by xhuytox** [comment]
Ahh, did not know that. Thanks for the clarification.

**Comment by halsafar** [comment]
There actually is a feature in SongBrowser but it is hidden.  You need to edit `song_browser_settings.xml` and set the key `randomInstantQueue` to `true`.  Then when you click Random it will shuffle and queue the first song.  Unfortunately it selects a random difficulty in the current build.

Open to suggestions.

**Comment by xhuytox** [comment]
The way Random works right now, there's a lot of potential for bugs and weird behaviors. My suggestion would be to get rid of the Random filter as we know it now and have a Dice button like in the song downloader mod; I believe it randomly scrolls to and selects a song from the current song list [see here](https://github.com/andruzzzhka/BeatSaverDownloader/blob/3d0ea3046488aabce00ab6edfe03b6ab4b2e00e9/BeatSaverDownloader/UI/SongListTweaks.cs#L192-L194). From what I can see, it just lets the game itself handle the difficulty selection, which is fine.

**Comment by halsafar** [comment]
We now have the dice button.  It just randomized the song list, maintains the order between songs or restarting the game.  It picks the top song for you but doesn't hit play.  Meeting everyone in the middle here.
