### ISSUE TITLE
Feature request: Remember last selected song pack

### ISSUE THREAD

**Issue by brian91292** [halsafar/BeatSaberSongBrowser#49]
As stated in the title, this would be an awesome feature. I've already written some code to scroll to the custom song pack in SyncSaber, here's a link for reference:

https://github.com/brian91292/SyncSaber/blob/d4c54429dce5660a1801929e389168dd0fbd0a97/SyncSaber/SongListUtils.cs#L129

It seems the ScrollToCellWithIndex function is actually broken for horizontal TableViews, though, so I've just simulated scrolling to the pack with the page buttons for now (I'm pretty sure this is a bug in vanilla beat saber).

**Comment by halsafar** [comment]
Definitely going to add this snippet to SongBrowser in the next update.  This will also help fix selecting the previous song when entering Solo/Party mode.  A feature I've had a few request I get working again.  The problem is it always defaults to OST 1 and rarely is your last song in that pack.

**Comment by halsafar** [comment]
I've got this mostly working in branch `feature-remember-levelpack`.

**Comment by halsafar** [comment]
@brian91292  Implemented into 3.0.4.

Confirm?

**Comment by halsafar** [comment]
A few versions later and I think this is working.  We can file new issues for specific bugs with it.
