### ISSUE TITLE
Filter breaking the songlist on return to main menu

### ISSUE THREAD

**Issue by Jujuedv** [halsafar/BeatSaberSongBrowser#52]
Steps to reproduce:

- Use search to filter your custom songs
- return to the main menu
- if you go back to custom songs and remove the filter the songs which did not apply to the filter do not return

This sometimes is combined with new songs downloaded ingame not appearing immediatly.

**Comment by xhuytox** [comment]
To add to this, Search itself seems to not be working. The behavior is that you can't type anything.

**Comment by halsafar** [comment]
@Jujuedv Confirmed this.  Will fix in next release.

@xhuytox Do you mean type with a keyboard?

**Comment by xhuytox** [comment]
@halsafar Disregard. I can't seem to reproduce it. Might've been just a fluke.

**Comment by fuyushi** [comment]
exact same issue with playlists selection/filter

**Comment by halsafar** [comment]
Confirmed.  Fix is incoming.

**Comment by halsafar** [comment]
I've got this fixed in the next release.  Should come any day.  Current `devel` branch.

**Comment by halsafar** [comment]
@Jujuedv @fuyushi Fixed in 3.0.4 release.  Confirm?

**Comment by halsafar** [comment]
With the fixes in 3.0.4 and the recent changes from @shrubin in 3.0.6 I believe this issue is fixed.  

There might be more paths to break the song list in similar ways but the reproduction steps in this issue no longer breaks it.
