### ISSUE TITLE
No Scores

### ISSUE THREAD

**Issue by kamegami13** [halsafar/BeatSaberSongBrowser#55]
I was having issues with the latest install where the Score screen would not appear and no scores would be saved in either Solo or Party mode. My eliminating mods I determined that SongBrowser 3.0.4. is what caused this issue. Removing SongBrowser or downgrading to 3.0.3. fixes the issues.

Steps to Reproduce:
Tested on BS v0.13.1
Modded with ModSaber 1.4.7 prior to the takedown today
Have SongBrowser 3.0.4 installed
Beat any song in Solo or Party mode
Observe that no Score or Player Select screen appears
Observe no new entry in the score board
Check the LocalLeaderboards.dat to show that new scores are not recorded there either

**Comment by xhuytox** [comment]
Piggybacking on this, another related issue is that when you try to restart a song from the pause menu, it brings you back to the song list.

**Comment by halsafar** [comment]
Both of these issues are fixed in 3.0.5.  We just released 3.0.6, if you want to give it a spin and confirm.

**Comment by halsafar** [comment]
This was working well in 3.0.6.
