### ISSUE TITLE
Can't access Solo or Party mode after installing SongBrowser

### ISSUE THREAD

**Issue by amasuke55** [halsafar/BeatSaberSongBrowser#61]
I can not click the Solo or Party buttons in the main menu after I install the SongBrowser plugin.
Campaign button works though.

**Comment by halsafar** [comment]
Is this still happening in version 3.0.6 (latest)?

Can you run the game with `--verbose` and post a copy of the log.

**Comment by halsafar** [comment]
No info.  Cannot reproduce.  We have progressed a few versions of Beat Saber and SongBrowser since this was reported.  Closing this.  Re-Open if more info is provided.
