### ISSUE TITLE
Sorting option doesn't seem to work

### ISSUE THREAD

**Issue by luigi2406** [halsafar/BeatSaberSongBrowser#7]
If I click on one of the playlists above the song selection, the songs don't get sorted differently. Also the playlist doesn't change until I back out of the song selection and go back in, so there is no visible change when clicking on one of the playlists above the songs

**Comment by halsafar** [comment]
Try 2.0-rc5.  Should fix it:
https://github.com/halsafar/BeatSaberSongBrowser/releases/tag/2.0-rc5

**Comment by luigi2406** [comment]
yep, the latest version fixed it. GJ :)

**Comment by halsafar** [comment]
Awesome!  Glad to hear.
