### ISSUE TITLE
PP sorting is not available

### ISSUE THREAD

**Issue by wgzeyu** [halsafar/BeatSaberSongBrowser#91]
In the past week, every time I opened BeatSaber, PP sorting could not be used. SongBrowser version is already 5.3.1.
![](https://wgzeyu.gtxcn.com/img/TIM%E5%9B%BE%E7%89%8720190721160902.png)
I looked for the problem seems to be due to the slowness of the CDN loading song data in China?
I tried it, 1.2MB of JSON, and I didn't download it for an hour.
![](https://wgzeyu.gtxcn.com/img/a4.gif)  
![](https://wgzeyu.gtxcn.com/img/TIM%E6%88%AA%E5%9B%BE20190721162629.png)  
The download speed is about 600KB/h and the packet loss rate is over 50%.
![](https://wgzeyu.gtxcn.com/img/TIM%E6%88%AA%E5%9B%BE20190721151836.png)  
But most CDNs or websites download speeds are normal, only this one CDN is so slow

**Comment by halsafar** [comment]
Has been working for awhile now.
Reopen if you still have issues.
