### ISSUE TITLE
Sorting breaks when EnhancedSearchAndFilters plugin is used

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [halsafar/BeatSaberSongBrowser#95]
Not sure who's issue this is.  But these 2 plugins USED to work fine together.  Please make them work together again.

Beatsaber 1.4.0 (cleanly reinstalled correctly :)  )
EnhancedSearchAndFilters 1.5.2
Song Browser 5.5.1

Link to initial bug report on the EnhancedSearchAndFilters plugin github:
https://github.com/chrislee0419/EnhancedSearchAndFilters/issues/3

[beatsaber filter plugin bug.zip](https://github.com/halsafar/BeatSaberSongBrowser/files/3694585/beatsaber.filter.plugin.bug.zip)

**Comment by chrislee0419** [comment]
Hey halsafar, turns out this issue was on my end (during my filtering process, it does a Dictionary.Add which fails if the user had duplicate songs).

You should be able to safely close this issue. Thanks!
